name: Build LaTeX Documents

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.tex'
      - '**.sty'
      - 'Common_Images/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.tex'
      - '**.sty'
      - 'Common_Images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Compile Lecture Notes
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: Lecture_Notes

    #   - name: Compile Slides (Week 01)
    #     uses: xu-cheng/latex-action@v3
    #     with:
    #       root_file: lecture1.tex
    #       working_directory: Slides/Week_01

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: |
            Lecture_Notes/main.pdf
            Slides/Week_01/lecture1.pdf
          retention-days: 30

      - name: Rename PDF
        if: success()
        run: cp Lecture_Notes/main.pdf "COMP0263 Lecture Notes 2026.pdf"

      - name: Upload to Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: "COMP0263 Lecture Notes 2026.pdf"
          tag_name: latest
          generate_release_notes: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
